'use client'

import React, { useEffect, useState } from 'react'

type User = { id:string; username:string; displayName:string; systemRole:string; resourceId:string|null; resourceName:string|null; active:boolean; mustChangePassword:boolean; temporaryPasswordExpiresAt:string|null; memberships:{ projectId:string; projectName:string; role:string }[] }
type Resource = { id:string; name:string }
type Project = { id:string; name:string }
const roles = ['SYSTEM_ADMIN', 'PORTFOLIO_MANAGER', 'STANDARD_USER', 'EXTERNAL_USER', 'SUSPENDED']
const projectRoles = ['PROJECT_ADMIN', 'PROJECT_MANAGER', 'TEAM_LEAD', 'CONTRIBUTOR', 'VIEWER']

export function UserManagementDialog({ onClose }: { onClose: () => void }) {
  const [users, setUsers] = useState<User[]>([]); const [resources, setResources] = useState<Resource[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [membershipProjectIds, setMembershipProjectIds] = useState<Record<string,string>>({})
  const [username, setUsername] = useState(''); const [displayName, setDisplayName] = useState(''); const [resourceId, setResourceId] = useState(''); const [systemRole, setSystemRole] = useState('STANDARD_USER'); const [notice, setNotice] = useState(''); const [error, setError] = useState('')
  async function load() { const [userResponse, resourceResponse, projectResponse] = await Promise.all([fetch('/api/users'), fetch('/api/resources'), fetch('/api/projects')]); if (userResponse.ok) setUsers(await userResponse.json()); if (resourceResponse.ok) setResources(await resourceResponse.json()); if (projectResponse.ok) setProjects(await projectResponse.json()) }
  useEffect(() => { void load() }, [])
  async function create(event: React.FormEvent) { event.preventDefault(); setError(''); const response = await fetch('/api/users', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ username, displayName, resourceId:resourceId || undefined, systemRole }) }); const data = await response.json().catch(() => ({})); if (!response.ok) return setError(data.error ?? 'Unable to create user.'); setNotice(`Temporary password for ${data.user.username}: ${data.temporaryPassword} (expires ${new Date(data.expiresAt).toLocaleDateString('th-TH')})`); setUsername(''); setDisplayName(''); setResourceId(''); await load() }
  async function update(userId:string, body:object) { setError(''); const response = await fetch(`/api/users/${userId}`, { method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body) }); const data = await response.json().catch(() => ({})); if (!response.ok) return setError(data.error ?? 'Unable to update user.'); if (data.temporaryPassword) setNotice(`Temporary password for ${data.user.username}: ${data.temporaryPassword} (expires ${new Date(data.expiresAt).toLocaleDateString('th-TH')})`); await load() }
  async function setMembership(userId:string, projectId:string, method:'PUT'|'DELETE', role='CONTRIBUTOR') { setError(''); const response = await fetch(`/api/users/${encodeURIComponent(userId)}/project-memberships/${encodeURIComponent(projectId)}`, { method, headers:{'Content-Type':'application/json'}, body:method === 'PUT' ? JSON.stringify({ role }) : undefined }); const data = await response.json().catch(() => ({})); if (!response.ok) return setError(data.error ?? 'Unable to update project access.'); await load() }
  return <div style={overlay}><section role="dialog" aria-modal="true" style={dialog}><header><strong>User Management</strong><button onClick={onClose} style={neutral}>×</button></header>{error && <p style={{color:'#B91C1C'}}>{error}</p>}<div style={{marginTop:16,overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12}}><thead><tr><th style={cell}>User</th><th style={cell}>Project access</th><th style={cell}>Account</th></tr></thead><tbody>{users.map(user=><tr key={user.id} style={{borderTop:'1px solid #EAECF0'}}><td style={cell}><strong>{user.displayName}</strong><br/>{user.username}</td><td style={cell}>{user.memberships.map(m=><div key={m.projectId} style={{marginBottom:5}}>{m.projectName} · <select value={m.role} onChange={e=>void setMembership(user.id,m.projectId,'PUT',e.target.value)} style={compact}>{projectRoles.map(role=><option key={role}>{role}</option>)}</select><button onClick={()=>void setMembership(user.id,m.projectId,'DELETE')} style={danger}>Remove</button></div>)}<div><select value={membershipProjectIds[user.id] ?? ''} onChange={e=>setMembershipProjectIds(current=>({...current,[user.id]:e.target.value}))} style={compact}><option value="">Add project…</option>{projects.filter(project=>!user.memberships.some(m=>m.projectId===project.id)).map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select><button disabled={!membershipProjectIds[user.id]} onClick={()=>void setMembership(user.id,membershipProjectIds[user.id],'PUT')} style={primary}>Add</button></div></td><td style={cell}><button onClick={()=>void update(user.id,{active:!user.active})} style={neutral}>{user.active?'Disable':'Enable'}</button></td></tr>)}</tbody></table></div></section></div>
}
const label={display:'block',fontSize:11,fontWeight:700,color:'#475467'}; const input={display:'block',width:'100%',marginTop:5,padding:'8px',border:'1px solid #D8DEE9',borderRadius:7,background:'#fff',fontSize:12,boxSizing:'border-box' as const}; const primary={border:'none',borderRadius:7,padding:'6px 9px',background:'#4F46E5',color:'#fff',fontWeight:800,cursor:'pointer'}; const cell={padding:'10px 8px',verticalAlign:'top'}; const neutral={border:'1px solid #D8DEE9',borderRadius:6,padding:'6px 8px',background:'#fff',color:'#475467',fontSize:11,cursor:'pointer'}; const danger={...neutral,borderColor:'#FECACA',color:'#B91C1C',background:'#FFF5F5',marginLeft:4}; const compact={padding:5,border:'1px solid #D8DEE9',borderRadius:6,fontSize:11}; const overlay={position:'fixed' as const,inset:0,zIndex:100,background:'rgba(15,23,42,.45)',display:'grid',placeItems:'center',padding:20}; const dialog={width:'min(900px,100%)',maxHeight:'calc(100vh - 40px)',overflow:'auto',background:'#fff',borderRadius:16,padding:24,fontFamily:'Arial,sans-serif'}
